#!/bin/bash

WINDOWS_ENTRY=`sed -n '/^menuentry/s/.*\(["'\''].*["'\'']\).*/\1/p' /boot/grub/grub.cfg | grep --line-number Windows`
MENU_NUMBER=$(( `echo $WINDOWS_ENTRY | sed -e "s/:.*//"` - 1 ))
sudo grub-reboot $MENU_NUMBER
xfce4-session-logout --reboot